#!/bin/bash
apt update && apt upgrade -y
apt install -y curl jq

LITESTREAM_VERSION=$(curl 'https://api.github.com/repos/benbjohnson/litestream/releases/latest' | jq -r .tag_name | sed 's/^v//')
HEADSCALE_VERSION=$(curl 'https://api.github.com/repos/juanfont/headscale/releases/latest' | jq -r .tag_name | sed 's/^v//')

curl -L "https://github.com/benbjohnson/litestream/releases/download/v${LITESTREAM_VERSION}/litestream-${LITESTREAM_VERSION}-linux-x86_64.deb" -o /tmp/litestream.deb
curl -L "https://github.com/juanfont/headscale/releases/download/v${HEADSCALE_VERSION}/headscale_${HEADSCALE_VERSION}_linux_amd64.deb" -o /tmp/headscale.deb

apt install -y /tmp/litestream.deb /tmp/headscale.deb

rm /tmp/litestream.deb /tmp/headscale.deb

apt remove -y curl jq && apt autoremove -y
apt clean
rm -rf /var/lib/apt/lists/*
